name: Sync Official Videos (Daily)

on:
  schedule:
    - cron: '0 4 * * *' # Daily at 04:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Supabase Edge Function
        env:
          FUNC_URL: ${{ secrets.SUPABASE_FUNCTION_URL_SYNC_OFFICIAL_VIDEOS }}
          SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          if [ -z "$FUNC_URL" ] || [ -z "$SERVICE_ROLE" ]; then
            echo "Missing secrets. Please set SUPABASE_FUNCTION_URL_SYNC_OFFICIAL_VIDEOS and SUPABASE_SERVICE_ROLE_KEY in your repository settings (Settings -> Secrets and variables -> Actions)."
            exit 1
          fi

          echo "=== DEBUG INFO ==="
          echo "Function URL: $FUNC_URL"
          echo "Service Role Key: ${SERVICE_ROLE:0:20}..."
          echo "Current time: $(date)"
          echo "=================="

          # Test basic connectivity first
          echo "Testing basic connectivity to Supabase..."
          curl -I "${FUNC_URL%/functions/v1/*}" --max-time 10 || echo "Warning: Base URL connectivity test failed"

          echo "Calling Edge Function with extended timeout..."

          # Make request with extended timeout and better error handling
          http_code=$(curl --silent --show-error --write-out "%{http_code}" \
            --max-time 300 \
            --connect-timeout 30 \
            -X POST "$FUNC_URL" \
            -H "Authorization: Bearer $SERVICE_ROLE" \
            -H "Content-Type: application/json" \
            -H "User-Agent: GitHub-Actions-CountryMusicHub/1.0" \
            -d '{"trigger":"github_actions","source":"gha","schedule":"daily_04_00_utc","timestamp":"'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"}' \
            -o response.json 2>error.log) || {
              echo "=== REQUEST FAILED ==="
              echo "HTTP Code: $http_code"
              echo "Error log:"
              cat error.log || echo "No error log available"
              echo "Response (if any):"
              cat response.json || echo "No response file created"
              
              # Check if it's a timeout specifically
              if grep -q "timeout" error.log 2>/dev/null; then
                echo "This appears to be a timeout issue. The function may be taking too long to execute."
                echo "Consider optimizing the Edge Function or increasing the timeout."
              fi
              
              exit 1
            }

          echo "=== REQUEST COMPLETED ==="
          echo "HTTP Status: $http_code"
          echo "Response:"
          cat response.json || echo "No response content"

          if [ "$http_code" -eq 504 ]; then
            echo "=== 504 GATEWAY TIMEOUT DETECTED ==="
            echo "This usually means:"
            echo "1. The Edge Function is taking longer than 30 seconds to execute"
            echo "2. Supabase infrastructure is experiencing issues"
            echo "3. The function URL might be incorrect"
            echo "Please check the Supabase Edge Functions logs for more details."
            exit 1
          elif [ "$http_code" -ge 400 ]; then
            echo "Non-success HTTP status: $http_code"
            exit 1
          else
            echo "✅ Success! Function executed successfully."
          fi
